Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Not Found: /sites/default/files/2022-07/groupe-173865.jpg
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /inscription/
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\http\request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\HP\django\ensae\home\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 9, in inscription_view
    if form.is_valid():
AttributeError: 'Inscription' object has no attribute 'is_valid'
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'article' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 20, in inscription_view
    inscription.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'article' in 'field list'")
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'article' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 20, in inscription_view
    inscription.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'article' in 'field list'")
C:\Users\HP\django\ensae\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'article' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 20, in inscription_view
    inscription.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'article' in 'field list'")
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'concours_articles.inscription_inscription' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 20, in inscription_view
    inscription.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'concours_articles.inscription_inscription' doesn't exist")
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /inscription/
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'concours_articles.inscription_inscription' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\inscription\views.py", line 20, in inscription_view
    inscription.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'concours_articles.inscription_inscription' doesn't exist")
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1049, "Unknown database 'concours_articles'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\django\ensae\home\views.py", line 20, in Accueil_view
    newsletter.save()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\models\sql\compiler.py", line 1655, in execute_sql
    with self.connection.cursor() as cursor:
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Anaconda\envs\mydjango\lib\site-packages\MySQLdb\connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1049, "Unknown database 'concours_articles'")
Watching for file changes with StatReloader
C:\Users\HP\django\ensae\home\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /{% static 'images/ADEPP.jpg}
Not Found: /{% static 'images/ADEPP.jpg'}
Not Found: /{% static 'images/ADEPP.jpg'}
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\Apropos\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\inscription\migrations\0001_initial.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\home\migrations\0001_initial.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\HP\django\RESA\home\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /127.0.0.1:8000/
Not Found: /favicon.ico
Not Found: /2n/2n6/2n6epi.woff2
Not Found: /2n/2n6/2n6epi.woff2
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
